### ISSUE TITLE
Crash on startup (Fabric 1.19.2)

### ISSUE THREAD

**Issue by spunchbop121** [KrLite/Bounced#1]
[latest.log](https://github.com/KrLite/Bounced/files/10326235/latest.log)

**Comment by KrLite** [comment]
Oh, I've just noticed that the parameter isn't the same between **1.19.2** and **1.19.3.** The parameter type `float` works in 1.19.3, but in 1.19.2 it was `double.` So the mixing apply failed. I'll fix the issue soon by splitting a version for 1.19.2 and lower. Thanks for reporting!

**Comment by KrLite** [comment]
Fixed in release 1.0.2.
