### ISSUE TITLE
[Compatibility] 'Slight' GUI Modifications Breaks the Mod on Quilt

### ISSUE THREAD

**Issue by Estrelaura** [KrLite/Bounced#11]
~~Both mods do something that breaks the animation on the screen when it's supposed to play a second time or after that. Perhaps a mixin conflict? Both are highly configurable, so raising the priority and letting the user figure out what features to use couldn't be that bad.~~

https://github.com/KrLite/Bounced/issues/11#issuecomment-1680321071

**Comment by KrLite** [comment]
Thanks for reporting! I shall check it soon!

**Comment by KrLite** [comment]
**Bounced** is actually working well on local tests, and nothing breaks the animation. It's weird that it is not behaving correctly on your side, could you please provide a screen recording or so?
Version tested: `1.20.1` `1.19.4` `1.19.3` `1.18.2`

**Comment by Estrelaura** [comment]
Totally my bad, it seems the mod breaking it is 'Slight' GUI Animations. It did seem like those two because sometimes it randomly works, so it seemed like removing them fixed it. A deeper test with less mods pointed to this one as the true culprit.

**Comment by KrLite** [comment]
Maybe some functions in **'Slight' GUI Modifications** broke **Bounced.** But with the default settings on `1.18.2`, they are working well together. Could you please provide informations about what you've enabled in **'Slight' GUI Modifications?**

**Comment by Estrelaura** [comment]
Sure. First of all i'm using Quilt 0.19.4, Minecraft is 1.20.1. The settings enabled are:

- Fluid Advancements
- Opening animations
-   Chat Animation
-   Slide in from bottom
-   Fade in
- Text Field Modifications
-   Module Enabled
-   Right Click Actions
- Right Click Actions

**Comment by KrLite** [comment]
Well that's weird, on `1.20.1 Quilt` with the default settings the animation breaks.

**Comment by KrLite** [comment]
**And it is only happening on Quilt.** With the same mod jars but on `1.20.1 Fabric`, everything goes well. That really makes me 🤯.

Bugs with Quilt are really hard to fix.. Maybe a separated jar is needed.

**Comment by KrLite** [comment]
Maybe I'll consider this issue later as this is related to Quilt (or **'Slight' GUI Modifications** on Quilt), not **Bounced** itself.
