### ISSUE TITLE
Curseforge Page.

### ISSUE THREAD

**Issue by murao-kun** [KrLite/Bounced#24]
### Write Something Here

Can you also make the mod available on curseforge? I am making a modpack in which I want to include the mod.
Would be very nice to also have curseforge page and make pack devs happy!
Thanks!

**Comment by KrLite** [comment]
Thanks for noting us. Since CurseForge is too difficult to use compared to Modrinth (that's cursed 😭), I haven't update it for a long time (this mod was my personal project at that time). But we will do it soon.

**Comment by TexBlock** [comment]
> Thanks for noting us. Since CurseForge is too difficult to use compared to Modrinth (that's cursed 😭), I haven't update it for a long time (this mod was my personal project at that time). But we will do it soon.

I think we can use the Gradle plugin for automated uploads so we don't have to do it manually (but the creation of the mod page may still have to be done manually).

**Comment by KrLite** [comment]
> > Thanks for noting us. Since CurseForge is too difficult to use compared to Modrinth (that's cursed 😭), I haven't update it for a long time (this mod was my personal project at that time). But we will do it soon.
> 
> I think we can use the Gradle plugin for automated uploads so we don't have to do it manually (but the creation of the mod page may still have to be done manually).

Sure! I will figure that out soon.

Although our mods seems to not be in vogue on CurseForge.

**Comment by KrLite** [comment]
I have just updated the files and descriptions. CurseForge is so difficult to use! It runs in Gateway Timeouts, it does not allow me to upload source files, and the version & dependency pickers are just like blocked loos! God bless we have Modrinth but the cursed FTB mods are CurseForge only, that's so cursed 😡.
