### ISSUE TITLE
[BUG]: Crash on version 3.1.0

### ISSUE THREAD

**Issue by Bibbly10** [KrLite/Bounced#26]
### Which Mod Loader are You Using?

Quilt

### What Happened?

Game crashes when I attempt to enter a world.

### Steps to Reproduce

1. Install Bounced 3.1.0 and the most recent Quilt/Fabric API
2. Launch the game and enter a world
3. Game crashes when the world loads (when the main menu unloads?)

### Crash Log

https://pastebin.com/6ZtC3Ues

### Anything Else?

I tested this on both Fabric and Quilt for 1.20.1 (no other mods except the necessary API mod) through the Prism Launcher and got the same results. I have attached the crashlog pastebin from the Quilt instance. I also tried Curseforge and got the same. I then tried it on Fabric for 1.20.2 and got the same result again.

Version 3.0.0 does not cause this crash.

**Comment by KrLite** [comment]
Thanks for reporting! Gonna make a quick fix.

**Comment by KrLite** [comment]
Fixed in `3.1.1`!
