### ISSUE TITLE
[BUG]: Crash on Forge 1.20.1

### ISSUE THREAD

**Issue by QwertRvg** [KrLite/Bounced#27]
### Which Mod Loader are You Using?

Forge

### What Happened?

It crashes the game before the in-game loading screen even appears.

### Steps to Reproduce

Download Forge 1.20.1 version 
Add to mods folder
Launch game

### Crash Log

https://pastebin.com/5YmbUe8S

### Anything Else?

It happens when the Remove Reloading Screen mod is added at the same time.

**Comment by KrLite** [comment]
@TexBlock please have a look. I suppose it's a mixin conflict.

**Comment by TexBlock** [comment]
@QwertRvg Please upload `latest.log`!

**Comment by TexBlock** [comment]
> @TexBlock please have a look. I suppose it's a mixin conflict.

maybe this is `Remove Reloading Screen` issue
