### ISSUE TITLE
[BUG]: Wrong jar uploaded to Modrinth

### ISSUE THREAD

**Issue by SplendidAlakey** [KrLite/Bounced#28]
### Which Mod Loader are You Using?

Fabric

### What Happened?

You've accidentally uploaded a dev jar, which will crash in production: https://modrinth.com/mod/bounced/version/4.1.0-fabric1.20.4

### Steps to Reproduce

https://cdn.modrinth.com/data/2mlOZXZr/versions/bbJQbjJ2/bounced-4.1.0-fabric1.20.4-dev.jar
or
https://cdn.modrinth.com/data/2mlOZXZr/versions/NVZWbHZz/bounced-4.1.0-fabric1.20-dev.jar - also incorrectly tagged

### Crash Log

https://gist.github.com/SplendidAlakey/58a99f46c0f90054611d03ab77941155

### Anything Else?

So far it's the latest 2 uploads that are affected.

**Comment by KrLite** [comment]
Good catch. The releases have been revoked and now re-released. I think they are OK now.

**Comment by liangmoe** [comment]
為啥bounced會有Stenographer的檔案 https://modrinth.com/mod/bounced/version/3.1.0-forge1.20.1

編輯: 馬上被刪了沒事了
