### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [KrLite/Bounced#29]
### Feature Description

/

### Propose Reason

/

**Comment by KrLite** [comment]
Sure. But first of all I need to live through my school examine week.

**Comment by venaminecraft** [comment]
Great, take your time 😄

**Comment by KrLite** [comment]
I'm back alive! **Bounced** is updated and now actively supports all versions from `1.20` to `1.21`. [Check it out `→`](https://modrinth.com/mod/bounced/version/4.1.1-fabric1.21)

**Comment by venaminecraft** [comment]
Thank you 😃
