### ISSUE TITLE
v1.0.4 does not appear compatible with 1.19.1

### ISSUE THREAD

**Issue by ComradeBlaze** [KrLite/Bounced#3]
Despite Modrinth saying the mod's compatible with 1.19 - 1.19.3, when running on 1.19.1 the loader throws up an error. 
![image](https://user-images.githubusercontent.com/87503727/214635397-8f5877f2-3f32-4cb3-8d83-2d289842cb7b.png)
![image](https://user-images.githubusercontent.com/87503727/214635522-3066769b-d0f1-49ea-a0c5-7605c8b20d6e.png)
Assuming it's probably just a mislabeling - should be easy fix. Seems like a fun mod, will use once I upgrade versions sometime. Thanks

**Comment by Aces-and-Jacks** [comment]
same with 1.19.2

**Comment by KrLite** [comment]
Oh that's when I set the wrong version on Modrinth, sorry! It will be fixed soon.
Bounced is only supporting 1.19.2 and 1.19.3, and there will be two different versions. Maybe Bounced for 1.19.2 can work on 1.19.1 but there's no plan supporting it.

**Comment by KrLite** [comment]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/68179735/214853475-8f6ecf2e-692d-4598-ad16-bb74caa132de.png">
It is fine now. I'm really sorry for that.

**Comment by ComradeBlaze** [comment]
No worries :)
