### ISSUE TITLE
[Suggestion] Title and Edition Bounce at different speeds

### ISSUE THREAD

**Issue by RyanCR03** [KrLite/Bounced#6]
suggestion to make the bounce speed of the "Java Edition" Section to be at a different speed or slightly offset from the main title

**Comment by KrLite** [comment]
That would be great. Thanks for the idea! Now it looks like:

https://user-images.githubusercontent.com/68179735/233754674-85fceb9e-94b2-4015-a3bc-1abc585fd64c.mov

Will be a part of version 2.1.0!

**Comment by KrLite** [comment]
ps. the total animation time for the subtitles is 936 milliseconds now, 73 slower than the animation time for the title.
